# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  archive:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      zipname: 'release_test.zip'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "start test"
          var=$(cat ./var.yml)
          echo "$var"
          echo "::set-env name=var_env::$var"
          echo ${{env.var_env}}
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.4.1
        with: 
          filename: ${{env.zipname}}
          exclusions: 'b.txt'

      - uses: actions/upload-artifact@v2
        with: 
          name: ${{env.zipname}}
          path: ./${{env.zipname}}

      - uses: actions/upload-artifact@v2
        with: 
          name: 'test'
          path: |
            a.txt
            b.txt

      - uses: actions/upload-artifact@v2
        with: 
          name: 'test3'
          path: "${{env.var_env}}"

  run_powershell:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: test_powershell
        shell: powershell
        run: ./PowerShell/test.ps1
